---
title: "Chronologies"
author: "Daniel Nielsen"
date: "Ongoing"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r set up}
library(ggplot2)
library(RColorBrewer)
library(tidyverse)
library(dplyr)
library(leaps)
library(dplR)
library(formattable)
tfd=read.csv("tfd.csv")
fdp=subset(tfd, tfdAll>=18.58)
```


```{r Lake Rebecca}
lrga=read.rwl("Measurements/LakeRebecca/LRGA.raw")
rwl.report(lrga)
corr.rwl.seg(lrga, seg.length=20, bin.floor=5)
lrga=subset(lrga, select=c(LR0509B,LR0509A,LR0409A,LR0409B,LR0416B,LR0419B,LR0413B,LR0413A,LR0309B,LR0306B,LR0305B,LR0305A,LR0304A,LR0309A,LR0306A,LR0307A,LR0206B,LR0206A,LR0110B))
rwl.report(lrga)
corr.rwl.seg(lrga, seg.length=20, bin.floor=5)
lrga=detrend(lrga, method="ModNegExp")
lrga=chron(lrga)
plot.crn(lrga,add.spline=TRUE, main="Lake Rebecca green ash")
lrae=read.rwl("Measurements/LakeRebecca/LRAE.raw")
rwl.report(lrae)
corr.rwl.seg(lrae, seg.length=20, bin.floor=5)
lrcw=read.rwl("Measurements/LakeRebecca/LRCW.raw")
rwl.report(lrcw)
corr.rwl.seg(lrcw, seg.length=20, bin.floor=5)
lrcw=subset(lrcw, select=c(LR0101A,LR0106B,LR0112B,LR0101B,LR0106A,LR0108B,LR0230B,LR0230A,LR0311A,LR0311B,LR0320A,LR0314A,LR0314B,LR0506A,LR0506B,LR0504A,LR0502A))
rwl.report(lrcw)
lrcw=detrend(lrcw,method='ModNegExp')
lrcw=chron(lrcw)
plot.crn(lrcw, add.spline=TRUE, main="Lake Rebecca cottonwood")
lrsm=read.rwl("Measurements/LakeRebecca/LRSM.raw")
rwl.report(lrsm)
corr.rwl.seg(lrsm, seg.length=20, bin.floor=5)
lrsm=subset(lrsm, select=c(LR0207B,LR0209B,LR0207A,LR0232A, LR0224A,LR0201B,LR0211B,LR0228B,LR0218B,LR0216B,LR0228A,LR0201A,LR0202B,LR0225A,LR0222B,LR0204B,LR0218A,LR0210B,LR0217A,LR0231B,LR0312A,LR0301A,LR0313B,LR0316B,LR0302B,LR0321A,LR0312B,LR0321B,LR0322A,LR0313A,LR0310A,LR0317B,LR0301B,LR0401B,LR0412B,LR0402A,LR0420A,LR0406A,LR0408A,LR0408B,LR0505B,LR0508B))
rwl.report(lrsm)
corr.rwl.seg(lrsm, seg.length=20, bin.floor=5)
lrsm=detrend(lrsm, method='ModNegExp')
lrsm=chron(lrsm)
plot.crn(lrsm, add.spline=TRUE, main="Lake Rebecca silver maple")
lrcw$year=seq(1917, 2017, 1)
lrga$year=seq(1914, 2017, 1)
lrsm$year=seq(1946, 2017, 1)
ggplot()+geom_line(data=lrga, aes(lrga$year, lrga$xxxstd, color='purple'))+geom_line(data=lrsm, aes(lrsm$year, lrsm$xxxstd, color='brown'))+geom_col(data=tfd, aes(Year, tfdAll/40, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*40, name="Total Days of Inundation"))+ggtitle("Lake Rebecca")+ylab("Ring Width Index")+xlab("Year (CE)")+theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), axis.title.y= element_text(size=20), title=element_text(size=30), axis.text.y=element_text(size=15), strip.text.x = element_text(size=15), legend.text=element_text(size=15))+scale_color_discrete(name="Species", labels=c("silver maple","green ash","total flood days"))
lrcl=read.csv("Climate datasets/LR.csv")
lrcw$year=seq(1917, 2017, 1)
lrga$year=seq(1914, 2017, 1)
lrsm$year=seq(1946, 2017, 1)
lrcl=subset(lrcl, year>=1914)
lrga=subset(lrga, year<=2016)
test=lm(lrga$xxxstd~lrcl$ppt)
summary(test)
test=lm(lrga$xxxstd~lrcl$tmin)
summary(test)
test=lm(lrga$xxxstd~lrcl$tmean)
summary(test)
test=lm(lrga$xxxstd~lrcl$tmax)
summary(test)
lrcl=subset(lrcl, year>=1917)
lrcw=subset(lrcw, year<=2016)
test=lm(lrcw$xxxstd~lrcl$ppt)
summary(test)
test=lm(lrcw$xxxstd~lrcl$tmin)
summary(test)
test=lm(lrcw$xxxstd~lrcl$tmean)
summary(test)
test=lm(lrcw$xxxstd~lrcl$tmax)
summary(test)
lrcl=subset(lrcl, year>=1946)
lrsm=subset(lrsm, year<=2016)
test=lm(lrsm$xxxstd~lrcl$ppt)
summary(test)
test=lm(lrsm$xxxstd~lrcl$tmin)
summary(test)
test=lm(lrsm$xxxstd~lrcl$tmean)
summary(test)
test=lm(lrsm$xxxstd~lrcl$tmax)
summary(test)
lrcw=subset(lrcw, year>=1972)
lrcw=subset(lrcw, year<=2011)
lrga=subset(lrga, year>=1972)
lrga=subset(lrga, year<=2011)
lrsm=subset(lrsm, year>=1972)
lrsm=subset(lrsm, year<=2011)
cor(lrcw$xxxstd, tfd$tfdAll, method='pearson')
cor(lrga$xxxstd, tfd$tfdAll, method='pearson')
cor(lrsm$xxxstd, tfd$tfdAll, method='pearson')
test=lm(lrsm$xxxstd~tfd$tfdAll)
summary(test)
test=lm(lrcw$xxxstd~tfd$tfdAll)
summary(test)
test=lm(lrga$xxxstd~tfd$tfdAll)
summary(test)
ggplot()+geom_point(aes(tfd$tfdAll,lrsm$xxxstd))+geom_smooth(aes(tfd$tfdAll,lrsm$xxxstd),method="lm")+ylab("Ring Width Index")+xlab("Total Growing Season Flood Days")+ggtitle("Lake Rebecca","silver maple")
ggplot()+geom_point(aes(tfd$tfdAll,lrga$xxxstd))+geom_smooth(aes(tfd$tfdAll,lrga$xxxstd),method="lm")+ylab("Ring Width Index")+xlab("Total Growing Season Flood Days")+ggtitle("Lake Rebecca","green ash")
ggplot()+geom_point(aes(tfd$tfdAll,lrcw$xxxstd))+geom_smooth(aes(tfd$tfdAll,lrcw$xxxstd),method="lm")+ylab("Ring Width Index")+xlab("Total Growing Season Flood Days")+ggtitle("Lake Rebecca","cottonwood")


ggplot()+geom_point(aes(tfd$tfdAll,lrsm$xxxstd), shape=1, color="red")+geom_smooth(aes(tfd$tfdAll,lrsm$xxxstd), color="red",method="lm")+geom_point(aes(tfd$tfdAll,lrga$xxxstd), shape=2, color="green")+geom_smooth(aes(tfd$tfdAll,lrga$xxxstd), color="green",method="lm")+geom_point(aes(tfd$tfdAll,lrcw$xxxstd), shape=3, color="purple")+geom_smooth(aes(tfd$tfdAll,lrcw$xxxstd), color="purple",method="lm")+ylab("Ring Width Index")+xlab("Total Growing Season Flood Days")+theme(axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), axis.title.y= element_text(size=25), title=element_text(size=30), axis.text.x=element_text(size=15), axis.text.y=element_text(size=15), strip.text.x = element_text(size=20))
```

```{r Indian Slough}
ishb=read.rwl("Measurements/IndianSlough/ISHB.raw")
rwl.report(ishb)
corr.rwl.seg(ishb, seg.length=20, bin.floor=5)
ishb=detrend(ishb, method="ModNegExp")
ishb=chron(ishb)
plot.crn(ishb, add.spline=TRUE, main="Indian Slough hackberry")
isga=read.rwl("Measurements/IndianSlough/ISGA.raw")
rwl.report(isga)
corr.rwl.seg(isga, seg.length=20, bin.floor=5)
issm=read.rwl("Measurements/IndianSlough/ISSM.raw")
rwl.report(issm)
corr.rwl.seg(issm, seg.length=20, bin.floor=5)
issm=subset(issm, select=c(IS0107A,IS0111B,IS0110B,IS0206A,IS0303A,IS0304A,IS0407A,IS0406A,IS0404A,IS0402A,IS0403A,IS0406A))
rwl.report(issm)
corr.rwl.seg(issm, seg.length=20, bin.floor=5)
issm=detrend(issm, method='ModNegExp')
issm=chron(issm)
plot.crn(issm, add.spline=TRUE, main="Indian Slough silver maple")
ishb$year=seq(1941, 2017, 1)
issm$year=seq(1904, 2017, 1)
ggplot()+geom_line(data=ishb, aes(ishb$year, ishb$xxxstd, color='green'))+geom_line(data=issm, aes(issm$year, issm$xxxstd, color='blue'))+geom_line(data=tfd, aes(tfd$Year,y=tfd$tfdGI/40, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*40))
iscl=read.csv("Climate datasets/IS.csv")
iscl=subset(iscl, year>=1904)
issm=subset(issm, year<=2016)
cor(issm$xxxstd, iscl$ppt, method='pearson')
cor(issm$xxxstd, iscl$tmin, method='pearson')
cor(issm$xxxstd, iscl$tmean, method='pearson')
cor(issm$xxxstd, iscl$tmax, method='pearson')
iscl=subset(iscl, year>=1941)
ishb=subset(ishb, year<=2016)
cor(ishb$xxxstd, iscl$ppt, method='pearson')
cor(ishb$xxxstd, iscl$tmin, method='pearson')
cor(ishb$xxxstd, iscl$tmean, method='pearson')
cor(ishb$xxxstd, iscl$tmax, method='pearson')
ishb=subset(ishb, year>=1972)
ishb=subset(ishb, year<=2011)
issm=subset(issm, year>=1972)
issm=subset(issm, year<=2011)
cor(ishb$xxxstd, tfd$tfdIS, method='pearson')
cor(issm$xxxstd, tfd$tfdIS, method='pearson')
test=lm(ishb$xxxstd~tfd$tfdIS)
summary(test)
test=lm(issm$xxxstd~tfd$tfdIS)
summary(test)

```

```{r Great River Harbor}
grga=read.rwl("Measurements/GreatRiverHarbor/GRGA.raw")
rwl.report(grga)
corr.rwl.seg(grga, seg.length=20, bin.floor=5)
grga=detrend(grga, method='ModNegExp')
grga=chron(grga)
plot.crn(grga, add.spline=TRUE, main="Great River Harbor green ash")
grsm=read.rwl("Measurements/GreatRiverHarbor/GRSM.raw")
rwl.report(grsm)
corr.rwl.seg(grsm, seg.length=20, bin.floor=5)
grsm=subset(grsm, select=c(GR0404A,GR0404B,GR0402B, GR0306B,GR0305A,GR0303B,GR0310A,GR0308A,GR0305B,GR0302B,GR0206A,GR0209A,GR0210A,GR0206B,GR0105A))
rwl.report(grsm)
corr.rwl.seg(grsm, seg.length=20, bin.floor=5)
grsm=detrend(grsm, method='ModNegExp')
grsm=chron(grsm)
plot.crn(grsm, add.spline=TRUE, main="Great River Harbor silver maple")
grga$year=seq(1939,2017,1)
grsm$year=seq(1913,2017,1)
ggplot()+geom_line(data=grga, aes(grga$year, grga$xxxstd, color='green'))+geom_line(data=grsm, aes(grsm$year, grsm$xxxstd, color='blue'))+geom_line(data=tfd, aes(tfd$Year,y=tfd$tfdGR/40, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*40))
grcl=read.csv("Climate datasets/GR.csv")
grcl=subset(grcl, year>=1939)
grga=subset(grga, year<=2016)
cor(grga$xxxstd, grcl$ppt, method='pearson')
cor(grga$xxxstd, grcl$tmin, method='pearson')
cor(grga$xxxstd, grcl$tmean, method='pearson')
cor(grga$xxxstd, grcl$tmax, method='pearson')
grga=subset(grga, year>=1972)
grga=subset(grga, year<=2011)
grsm=subset(grsm, year>=1972)
grsm=subset(grsm, year<=2011)
cor(grga$xxxstd, tfd$tfdGR, method='pearson')
cor(grsm$xxxstd, tfd$tfdGR, method='pearson')
test=lm(grga$xxxstd~tfd$tfdGR)
summary(test)
test=lm(grsm$xxxstd~tfd$tfdGR)
summary(test)
ggplot()+geom_point(aes(tfd$tfdGR, grsm$xxxstd), shape=15, color='darkgreen')+geom_smooth(aes(tfd$tfdGR, grsm$xxxstd),method='lm', color='darkgreen')+geom_point(aes(tfd$tfdGR, grga$xxxstd), shape=18, color='darkorange', size=2)+geom_smooth(aes(tfd$tfdGR, grga$xxxstd), method='lm', color='darkorange')+ylab("RWI")+xlab("Total Flood Days")+ggtitle("Increment Growth Responses Among Species","Great River Harbor")+theme(axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), axis.title.y= element_text(size=25), axis.title.x=element_text(size=25), title=element_text(size=35), axis.text.y=element_text(size=20),axis.text.x=element_text(size=20), strip.text.x = element_text(size=20))
```

```{r Minnesota City Boat Club}
bcae=read.rwl("Measurements/mlbcae.raw")
bccw=read.rwl("Measurements/BCCW.raw")
rwl.report(bccw)
corr.rwl.seg(bccw, seg.length=20, bin.floor=5)
bccw=subset(bccw, select=c(BC0202A,BC0201B,BC0105B,BC0211A,BC0209A,BC0201A,BC0105A,BC0202B,BC0211B,BC0206B))
rwl.report(bccw)
corr.rwl.seg(bccw, seg.length=20, bin.floor=5)
bccw=detrend(bccw, method='ModNegExp')
bccw=chron(bccw)
plot.crn(bccw, add.spline=TRUE, main='Boat Club cottonwood')
bccw$year=seq(1936,2017,1)
bcga=read.rwl("Measurements/mlbcga.raw")
rwl.report(bcga)
corr.rwl.seg(bcga, seg.length=20, bin.floor=5)
bcga=detrend(bcga, method='ModNegExp')
bcga=chron(bcga)
plot.crn(bcga, add.spline=TRUE, main='BCML green ash')
bcga$year=seq(1940,2017,1)
bchb=read.rwl("Measurements/mlbchb.raw")
rwl.report(bchb)
corr.rwl.seg(bchb, seg.length=20, bin.floor=5)
bchb=detrend(bchb, method='ModNegExp')
bchb=chron(bchb)
plot.crn(bchb, add.spline=TRUE, main='MLBC hackberry')
bchb$year=seq(1958,2017,1)
ggplot()+geom_line(data=bccw, aes(bccw$year, bccw$xxxstd, color='green'))+geom_line(data=bcga, aes(bcga$year, bcga$xxxstd, color='blue'))+geom_line(data=bchb, aes(bchb$year, bchb$xxxstd, color='brown'))+geom_line(data=tfd, aes(tfd$Year,y=tfd$tfdBC/30, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*30))+theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), axis.title.y= element_text(size=20), title=element_text(size=30), axis.text.y=element_text(size=15), strip.text.x = element_text(size=15), legend.text=element_text(size=15))+scale_color_discrete(name="Species", labels=c("hackberry","green ash","cottonwood","total flood days"))+ylab("Ring Width Index")+xlab("Year (CE)")+ggtitle("Minnesota City Boat Club")
bccw=subset(bccw, year>=1972)
bccw=subset(bccw, year<=2011)
bcga=subset(bcga, year>=1972)
bcga=subset(bcga, year<=2011)
bchb=subset(bchb, year>=1972)
bchb=subset(bchb, year<=2011)
cor(bccw$xxxstd, tfd$tfdBC, method='pearson')
cor(bcga$xxxstd, tfd$tfdBC, method='pearson')
cor(bchb$xxxstd, tfd$tfdBC, method='pearson')
test=lm(bccw$xxxstd~tfd$tfdBC)
summary(test)
test=lm(bcga$xxxstd~tfd$tfdBC)
summary(test)
test=lm(bchb$xxxstd~tfd$tfdBC)
summary(test)
bccl=read.csv("Climate Datasets/BC.csv")
ggplot()+geom_line(data=bccw, aes(bccw$year, bccw$xxxstd, color='blue'))+geom_line(data=bcga, aes(bcga$year, bcga$xxxstd, color='red'))+geom_line(data=bchb, aes(bchb$year,bchb$xxxstd, color='green'))+geom_line(data=bccl, aes(bccl$year, bccl$ppt/40, color='orange'))+geom_line(data=bccl, aes(bccl$year, bccl$tmin/40, color='yellow'))+geom_line(data=bccl, aes(bccl$year, bccl$tmean/40, color='purple'))+geom_line(data=bccl, aes(bccl$year, bccl$tmax/40, color='pink'))
bccw=subset(bccw, year>=1958)
bccw=subset(bccw, year<=2016)
bcga=subset(bcga, year>=1958)
bcga=subset(bcga, year<=2016)
bchb=subset(bchb, year>=1958)
bchb=subset(bchb, year<=2016)
bccl=subset(bccl, year>=1958)
bccl=subset(bccl, year<=2016)
cor(bccw$xxxstd, bccl$ppt, method='pearson')
cor(bcga$xxxstd, bccl$ppt, method='pearson')
cor(bchb$xxxstd, bccl$ppt, method='pearson')
cor(bccw$xxxstd, bccl$tmin, method='pearson')
cor(bcga$xxxstd, bccl$tmin, method='pearson')
cor(bchb$xxxstd, bccl$tmin, method='pearson')
cor(bccw$xxxstd, bccl$tmean, method='pearson')
cor(bcga$xxxstd, bccl$tmean, method='pearson')
cor(bchb$xxxstd, bccl$tmean, method='pearson')
cor(bccw$xxxstd, bccl$tmax, method='pearson')
cor(bcga$xxxstd, bccl$tmax, method='pearson')
cor(bchb$xxxstd, bccl$tmax, method='pearson')
```

```{r McNally}

```

```{r Bagley Bottoms}
bbsm=read.rwl("Measurements/Bagley/BBSM.raw")
rwl.report(bbsm)
corr.rwl.seg(bbsm, seg.length=20, bin.floor=5)
bbsm=subset(bbsm, select=c(BB1008A,BB0901A,BB0911A,BB0914A,BB0913B,BB0915B,BB0906A,BB0902A,BB0911B,BB0918B,BB0910B,BB0905B,BB0918A,BB0910B,BB0905B,BB0918A,BB0916B,BB0910A,BB0912B,BB0902B,BB0803B,BB0805A,BB0803A,BB0801B, BB0802B,BB0806B,BB0712A,BB0708A,BB0707A,BB0712B,BB0703A,BB0507A,BB0506A,BB0508A,BB0405A,BB0406A,BB0410A,BB0402C,BB0402A,BB0405B,BB0312A,BB0307A,BB0303B,BB0305A,BB0302B,BB0311A,BB0213A,BB0209A,BB0209B,BB0205B,BB0206A,BB0212A,BB0207A,BB0206B,BB0103A,BB0103B,BB0102A,BB0105B,BB0108A,BB0104A,BB0105A,BB0109B,BB0106B,BB0102B,BB0106A,BB0101A,BB0101B))
rwl.report(bbsm)
corr.rwl.seg(bbsm, seg.length=20, bin.floor=5)
bbsm=detrend(bbsm, method='ModNegExp')
bbsm=chron(bbsm)
plot.crn(bbsm, add.spline=TRUE, main='Bagley silver maple')
bbsm$year=seq(1921,2017,1)
bbae=read.rwl("Measurements/Bagley/BBAE.rwl")
rwl.report(bbae)
corr.rwl.seg(bbae, seg.length=20, bin.floor=5)
bbae=subset(bbae, select=c(BB0907B,BB0807A,BB0809A,BB0807B,BB0211B,BB0204A,BB0201A,BB0202B,BB0315B,BB0310B,BB0310A,BB0316A,BB0404A,BB0404B,BB0709B,BB0711B))
rwl.report(bbae)
corr.rwl.seg(bbae, seg.length=20, bin.floor=5)
bbae=detrend(bbae, method='ModNegExp')
bbae=chron(bbae)
plot.crn(bbae, add.spline=TRUE, main='Bagley American elm')
bbae$year=seq(1934,2017,1)
bbga=read.rwl("Measurements/Bagley/BBGA.raw")
rwl.report(bbga)
corr.rwl.seg(bbga, seg.length=20, bin.floor=5)
bbga=subset(bbga, select=c(BB0706A,BB0706B,BB0702A,BB0702B,BB0401A,BB0401B,BB0309A,BB0309B,BB0301B))
rwl.report(bbga)
corr.rwl.seg(bbga, seg.length=20, bin.floor=5)
bbga=detrend(bbga, method='ModNegExp')
bbga=chron(bbga)
plot.crn(bbga, add.spline=TRUE, main='Bagley green ash')
bbga$year=seq(1949, 2017, 1)
ggplot()+geom_line(data=bbae, aes(bbae$year, bbae$xxxstd, color='green'))+geom_line(data=bbga, aes(bbga$year, bbga$xxxstd, color='blue'))+geom_line(data=bbsm, aes(bbsm$year, bbsm$xxxstd, color='brown'))+geom_line(data=tfd, aes(tfd$Year,y=tfd$tfdBB/40, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*40))+ylab("Ring Width Index")+theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), axis.title.y= element_text(size=20), title=element_text(size=30), axis.text.y=element_text(size=15), strip.text.x = element_text(size=15), legend.text=element_text(size=15))+scale_color_discrete(name="Species", labels=c("American elm","green ash","silver maple","total flood days"))+ggtitle("Bagley Bottoms")
bbae=subset(bbae, year>=1972)
bbae=subset(bbae, year<=2011)
bbga=subset(bbga, year>=1972)
bbga=subset(bbga, year<=2011)
bbsm=subset(bbsm, year>=1972)
bbsm=subset(bbsm, year<=2011)
cor(bbae$xxxstd, tfd$tfdBB, method='pearson')
cor(bbga$xxxstd, tfd$tfdBB, method='pearson')
cor(bbsm$xxxstd, tfd$tfdBB, method='pearson')
test=lm(bbae$xxxstd~tfd$tfdBB)
summary(test)
test=lm(bbga$xxxstd~tfd$tfdBB)
summary(test)
test=lm(bbsm$xxxstd~tfd$tfdBB)
summary(test)
bbcl=read.csv("Climate Datasets/BB.csv")
ggplot()+geom_line(data=bbga, aes(bbga$year, bbga$xxxstd, color='blue'))+geom_line(data=bbae, aes(bbae$year, bbae$xxxstd, color='red'))+geom_line(data=bbsm, aes(bbsm$year,bbsm$xxxstd, color='green'))+geom_line(data=bbcl, aes(bbcl$Year, bbcl$ppt/40, color='orange'))+geom_line(data=bbcl, aes(bbcl$Year, bbcl$tMin/40, color='yellow'))+geom_line(data=bbcl, aes(bbcl$Year, bbcl$tMean/40, color='purple'))+geom_line(data=bbcl, aes(bbcl$Year, bbcl$tMax/40, color='pink'))
bbae=subset(bbae, year>=1949)
bbae=subset(bbae, year<=2016)
bbga=subset(bbga, year>=1949)
bbga=subset(bbga, year<=2016)
bbsm=subset(bbsm, year>=1949)
bbsm=subset(bbsm, year<=2016)
bbcl=subset(bbcl, Year>=1949)
bbcl=subset(bbcl, Year<=2016)
cor(bbae$xxxstd, bbcl$ppt, method='pearson')
cor(bbga$xxxstd, bbcl$ppt, method='pearson')
cor(bbsm$xxxstd, bbcl$ppt, method='pearson')
cor(bbae$xxxstd, bbcl$tMin, method='pearson')
cor(bbga$xxxstd, bbcl$tMin, method='pearson')
cor(bbsm$xxxstd, bbcl$tMin, method='pearson')
cor(bbae$xxxstd, bbcl$tMean, method='pearson')
cor(bbga$xxxstd, bbcl$tMean, method='pearson')
cor(bbsm$xxxstd, bbcl$tMean, method='pearson')
cor(bbae$xxxstd, bbcl$tMax, method='pearson')
cor(bbga$xxxstd, bbcl$tMax, method='pearson')
cor(bbsm$xxxstd, bbcl$tMax, method='pearson')
```

```{r Goose Island}
giga=read.rwl("Measurements/GooseIsland/GIGA.raw")
rwl.report(giga)
corr.rwl.seg(giga, seg.length=16, bin.floor=5)
giga=subset(giga, select=c(GI0201B, GI0405A,GI0501A,GI0501B,GI0507B,GI0502B,GI0602B,GI0602A,GI0911B,GI0909B,GI0909A,GI0902B,GI1201A,GI1206B,GI1202B,GI1206A,GI1202A,GI1408A,GI1407A,GI1501B,GI1501A,GI1503B))
rwl.report(giga)
corr.rwl.seg(giga, seg.length=20, bin.floor=5)
giga=detrend(giga, method = "ModNegExp")
giga=chron(giga)
plot.crn(giga, add.spline=TRUE, main="Goose Island green ash")
giga$year=seq(1918,2017,1)
gioak=read.rwl("Measurements/GooseIsland/GIOK.raw")
rwl.report(gioak)
corr.rwl.seg(gioak, seg.length=20, bin.floor=5)
gioak=subset(gioak, select=c(GI1403A,GI1404A,GI1403B,GI1402A,GI1404B,GI1402B,GI1406A,GI1406B,GI1309A,GI1309B,GI1307B,GI1304A,GI1302B,GI1303B,GI1304B,GI1303A,GI1305A,GI1306B,GI1302A,GI1305B,GI1205A,GI1203B,GI1205B,GI0905B,GI0601B,GI0404B,GI0404A))
rwl.report(gioak)
corr.rwl.seg(gioak,seg.length=20,bin.floor=5)
gioak=detrend(gioak, method="ModNegExp")
gioak=chron(gioak)
plot.crn(gioak,add.spline=TRUE, main="Goose Island oak")
gioak$year=seq(1901, 2017, 1)
giae=read.rwl('Measurements/GooseIsland/GIAE.raw')
rwl.report(giae)
gicw=read.rwl('Measurements/GooseIsland/GICW.raw')
rwl.report(gicw)
gihb=read.rwl('Measurements/GooseIsland/GIHB.raw')
rwl.report(gihb)
corr.rwl.seg(gihb, seg.length=18, bin.floor=5)
gihb=detrend(gihb, method='ModNegExp')
gihb=chron(gihb)
plot.crn(gihb, add.spline=TRUE, main='Goose Island hackberry')
gihb$year=seq(1979,2017,1)
gism=read.rwl('Measurements/GooseIsland/GISM.raw')
rwl.report(gism)
corr.rwl.seg(gism, seg.length=20, bin.floor=5)
gism=subset(gism, select=c(GI0211A,GI0212A,GI0210A,GI0211B,GI0213B,GI0206B,GI0217A,GI0214B,GI0212B,GI0215B,GI0217B))
rwl.report(gism)
corr.rwl.seg(gism, seg.length=20,bin.floor=5)
gism=detrend(gism, method='ModNegExp')
gism=chron(gism)
plot.crn(gism, add.spline=TRUE, main='Goose Island silver maple')
gism$year=seq(1943,2017,1)
girb=read.rwl('Measurements/GooseIsland/GIRB.raw')
rwl.report(girb)
corr.rwl.seg(girb, seg.length=20, bin.floor=5)
girb=subset(girb, select=c(GI0609B, GI0604B,GI0606A,GI0609A,GI0608A,GI0603B,GI0603A,GI1002B,GI1002A,GI1001A,GI1001B,GI1006B,GI1207A,GI1301B,GI1514A,GI1506B,GI1509A,GI1514B,GI1509B,GI1511B,GI1506A,GI1515B,GI1511A,GI1508A))
rwl.report(girb)
corr.rwl.seg(girb, seg.length=20, bin.floor=5)
girb=detrend(girb, method='ModNegExp')
girb=chron(girb)
plot.crn(girb, add.spline=TRUE, main='Goose Island river birch')
girb$year=seq(1943, 2017, 1)
ggplot()+geom_line(data=gioak, aes(gioak$year, gioak$xxxstd, color='blue'))+geom_line(data=giga, aes(giga$year, giga$xxxstd, color='red'))+geom_line(data=gihb, aes(gihb$year, gihb$xxxstd, color='purple'))+geom_line(data=girb, aes(girb$year, girb$xxxstd, color='orange'))+geom_line(data=gism, aes(gism$year, gism$xxxstd))+geom_line(data=tfd, aes(tfd$Year,y=tfd$tfdGI/30, color='red'))+scale_y_continuous(sec.axis = sec_axis(~.*30))+xlab("Year (CE)")+ylab("RWI")
gicl=read.csv("Climate datasets/GI.csv")
gicl=subset(gicl, year>=1901)
gioak=subset(gioak, year<=2016)
cor(gioak$xxxstd, gicl$ppt, method='pearson')
cor(gioak$xxxstd, gicl$tmin, method='pearson')
cor(gioak$xxxstd, gicl$tmean, method='pearson')
cor(gioak$xxxstd, gicl$tmax, method='pearson')
gioak=subset(gioak, year>=1972)
gioak=subset(gioak, year<=2011)
giga=subset(giga, year>=1972)
giga=subset(giga, year<=2011)
girb=subset(girb, year>=1972)
girb=subset(girb, year<=2011)
gihb=subset(gihb, year>=1972)
gihb=subset(gihb, year<=2011)
gism=subset(gism, year>=1972)
gism=subset(gism, year<=2011)
cor(gioak$xxxstd, tfd$tfdGI, method='pearson')
cor(giga$xxxstd, tfd$tfdGI, method='pearson')
cor(girb$xxxstd, tfd$tfdGI, method='pearson')
cor(gism$xxxstd, tfd$tfdGI, method='pearson')
test=lm(gioak$xxxstd~tfd$tfdGI)
summary(test)
test=lm(giga$xxxstd~tfd$tfdGI)
summary(test)
test=lm(girb$xxxstd~tfd$tfdGI)
summary(test)
test=lm(gism$xxxstd~tfd$tfdGI)
summary(test)
tfd=subset(tfd, Year>=1979)
cor(gihb$xxxstd, tfd$tfdGI, method='pearson')
test=lm(gihb$xxxstd~tfd$tfdGI)
summary(test)
```

```{r silver maple regression}
tfd=read.csv("tfd.csv")
ggplot()+geom_point(aes(tfd$tfdAll,lrsm$xxxstd))+geom_smooth(aes(tfd$tfdAll,lrsm$xxxstd),method="lm")
test=lm(lrsm$xxxstd~tfd$tfdAll)
summary(test)
ggplot()+geom_point(aes(tfd$tfdGR, grsm$xxxstd))+geom_smooth(aes(tfd$tfdGR, grsm$xxxstd), method='lm')
test=lm(grsm$xxxstd~tfd$tfdGR)
summary(test)
ggplot()+geom_point(aes(tfd$tfdBB, bbsm$xxxstd))+geom_smooth(aes(tfd$tfdBB, bbsm$xxxstd), method='lm')
test=lm(bbsm$xxxstd~tfd$tfdBB)
summary(test)
ggplot()+geom_point(aes(tfd$tfdAll,lrsm$xxxstd))+geom_point(aes(tfd$tfdGR, grsm$xxxstd))+geom_point(aes(tfd$tfdBB, bbsm$xxxstd))+ylab("Silver Maple RWI")+xlab("Total Annual Flood Days")
data=read.csv("rwi2.csv")
ggplot()+geom_point(data=data, aes(tfd, xxxstd, size=1))+geom_smooth(data=data, aes(tfd, xxxstd, size=1), method='lm')+ylab("Silver Maple RWI")+xlab("Total Annual Flood Days")+theme(axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), legend.position = "none", axis.title.y= element_text(size=25), title=element_text(size=30),axis.text.x=element_text(size=20), axis.text.y=element_text(size=15), strip.text.x = element_text(size=15))+facet_wrap(data$Site, nrow=5)
ggplot()+geom_point(data=data, aes(tfd, xxxstd))+geom_smooth(data=data, aes(tfd, xxxstd), method='lm')+ylab("Silver Maple RWI")+xlab("Total Annual Flood Days")+theme(axis.ticks.x = element_blank(), axis.ticks.y=element_blank(), legend.position = "none")+facet_wrap(data$Site, nrow=5)+ggtitle("Silver Maple Growth Patterns Differ Among Stands")
test=lm(data$xxxstd~data$tfd)
summary(test)
test=lm(bbsm$xxxstd~tfd$tfdBB)
summary(test)
test=lm(issm$xxxstd~tfd$tfdIS)
summary(test)
test=lm(gism$xxxstd~tfd$tfdGI)
summary(test)
test=lm(grsm$xxxstd~tfd$tfdGR)
summary(test)
test=lm(lrsm$xxxstd~tfd$tfdAll)
summary(test)
```
